### PR TITLE
fix(bedrock): correct URL encoding for model params

### LINKED ISSUE #740: Using the application inference profile in Bedrock results in failed model invocations.
Amazon Bedrock has added a new feature called "application inference profiles". 

Using application inference profiles is like adding an alias to a base model.

* Creating an application inference profile

```python
import boto3

bedrock = boto3.Session(region_name="us-west-2").client("bedrock")

# Create application inference profile
response = bedrock.create_inference_profile(
    inferenceProfileName="sonnet-inference-profile",
    modelSource={
        "copyFrom": "arn:aws:bedrock:us-west-2:637423213562:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    },
)

inference_profile_arn = response["inferenceProfileArn"]
print(inference_profile_arn)
```

> arn:aws:bedrock:us-west-2:637423213562:application-inference-profile/hq2of259skzs

For Bedrock's Invoke Model, you can specify the application inference profile as the modelId.

```python
import json

bedrock_runtime = boto3.Session(region_name="us-west-2").client("bedrock-runtime")

response = bedrock_runtime.invoke_model(
    modelId=inference_profile_arn,
    body=json.dumps(
        {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 1000,
            "messages": [
                {
                    "role": "user",
                    "content": "Hello!",
                }
            ],
        }
    ),
)

response_body = json.loads(response.get("body").read())
print(response_body["content"][0]["text"])
```

However, when using the Anthropic SDK, specifying the application inference profile as the model results in an error.

```python
anthropic = AnthropicBedrock(aws_region="us-west-2")

response = anthropic.messages.create(
    model=inference_profile_arn,
    max_tokens=1024,
    messages=[{"role": "user", "content": "Hello!"}],
)

print(response)
```

> Message(id=None, content=None, model=None, role=None, stop_reason=None, stop_sequence=None, type=None, usage=None, Output={'__type': 'com.amazon.coral.service#UnknownOperationException'}, Version='1.0')

This is likely because the model parameter is not expecting an ARN to be set.

Please let me know if you have any further questions regarding this.

### PR DESCRIPTION
**Pull request by moritalous**
This pull request fixes an issue #740 by using Bedrock's Application Profile.

### CODE REVIEW

**Comment by RobertCraigie** [comment]
Ah thanks for tracking this down and opening a PR! Would you be able to add a unit test for this case to `tests/lib/test_bedrock.py`?

**Comment by moritalous** [comment]
The ARN of the Application Profile contains a unique inference_profile_id that is automatically assigned, but how should I write it?

I have the following ARN in my environment, but it will be a different ID in other AWS environments.

arn:aws:bedrock:us-east-1:637423213562:application-inference-profile/jf2sje1c0jnb

**Comment by RobertCraigie** [comment]
ah the test shouldn't hit the live API, all of our tests hit mocks.

here's an example from the `test_bedrock.py` file
```py
@pytest.mark.respx()
def test_messages_retries(respx_mock: MockRouter) -> None:
    respx_mock.post(re.compile(r"https://bedrock-runtime\.us-east-1\.amazonaws\.com/model/.*/invoke")).mock(
        side_effect=[
            httpx.Response(500, json={"error": "server error"}, headers={"retry-after-ms": "10"}),
            httpx.Response(200, json={"foo": "bar"}),
        ]
    )
    sync_client.messages.create(
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": "Say hello there!",
            }
        ],
        model="anthropic.claude-3-sonnet-20240229-v1:0",
    )

    calls = cast("list[MockRequestCall]", respx_mock.calls)

    assert len(calls) == 2

    assert (
        calls[0].request.url
        == "https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke"
    )
    assert (
        calls[1].request.url
        == "https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke"
    )

```

**Comment by moritalous** [comment]
Thanks, I've added the test code.

**Review by JCuomo — APPROVED** [review]
tested and working!

**Review by RobertCraigie — APPROVED** [review]
Thanks!

**Pull request merged**
