### PR TITLE
feat(client): add the number of API call retries to the raw response API

### LINKED ISSUE #608: Feature request: return the number of failed attempts
You allow a parameter "max_retries". It would be great to return along with the API answer the number of "failed" API calls so that people have an idea of the load.

I don't know what your policy towards outside contributions is but if you agree I can implement it.

### PR DESCRIPTION
**Pull request by NDV-tiime**
Closes #608.

**Changes proposed:**

- Add the number of API call retries to the raw response API.

**Example:**

```
response = client.messages.with_raw_response.create(...)
response.retry_count # 0
```

### CODE REVIEW

**Comment by RobertCraigie** [comment]
Thanks for the PR! Could you add some unit tests to `tests/test_client.py`? Let me know if you need any guidance :)

**Comment by georgalis** [comment]
It would be great to see error details/statistics with Claude as well. I notice reduced performance, network error messages, and prompt resets are correlated together. It is difficult to predict this load and unfortunate to see my message remaining count de-increment with prompt resets, when I am certain there is no network issue on my side.

**Comment by NDV-tiime** [comment]
> Thanks for the PR! Could you add some unit tests to `tests/test_client.py`? Let me know if you need any guidance :)

Thank you, I just added some unit tests, are the tests good like that for you?

**Comment by RobertCraigie** [comment]
LGTM! I pushed a couple commits with some minor changes :)

We haven't fully decided on the `retry_count` name internally so I'm going to hold off on merging until then. Should hopefully be later today / tomorrow.

**Review by RobertCraigie — APPROVED** [review]
@NDV-tiime we landed on `retries_taken`! I've updated the PR and will merge shortly :)

**Comment by RobertCraigie** [comment]
Sorry for the delay and thanks for the PR!

**Pull request merged**
